services:
  plugin.manager.owned_config:
    class: Drupal\config_owner\OwnedConfigManager
    arguments: ['@module_handler', '@config_owner.config_dependency_validator']
  config_owner.storage_comparer_factory:
    class: Drupal\config_owner\OwnedConfigStorageComparerFactory
    arguments: ['@config.manager', '@config.storage', '@plugin.manager.owned_config']
  config_owner.config_dependency_validator:
    class: Drupal\config_owner\ConfigDependencyValidator
    arguments: ['@config.storage', '@config.factory']
