services:
  plugin.manager.owned_config:
    class: Drupal\config_owner\OwnedConfigManager
    arguments: ['@module_handler', '@cache.discovery', '@config_owner.config_dependency_validator']
  config_owner.storage_comparer_factory:
    class: Drupal\config_owner\OwnedConfigStorageComparerFactory
    arguments: ['@config.manager', '@config.storage', '@plugin.manager.owned_config']
  config_owner.event_subscriber:
    class: Drupal\config_owner\EventSubscriber\OwnedConfigEventSubscriber
    arguments: ['@plugin.manager.owned_config', '@cache.discovery']
    tags:
      - { name: event_subscriber }
  config_owner.config_dependency_validator:
    class: Drupal\config_owner\ConfigDependencyValidator
    arguments: ['@config.storage', '@config.factory']

